version: '2'
services:
  couchdb:
    image: couchdb:3.1.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=couchdb
    ports:
      - '5984:5984'
    tty: true
  elasticsearch:
    image: elasticsearch:7.14.0
    environment:
      - 'http.host=0.0.0.0'
      - 'transport.host=127.0.0.1'
      - 'discovery.type=single-node'
    ports :
      - '127.0.0.1:9200:9200'
    tty: true